In [1]:
import numpy as np
import matplotlib.pyplot as plt


In [27]:
Ne = 800
Ni =200
re = np.random.random((Ne,1))
ri = np.random.random((Ni,1))
a = np.concatenate([0.02*np.ones((Ne,1)), 0.02+0.08*ri])
b = np.concatenate([0.2*np.ones((Ne,1)), 0.25 - 0.05*ri])
c = np.concatenate([-65 + 15*re**2, -65*np.ones((Ni,1))])
d = np.concatenate([8 - 6*re**2, 2*np.ones((Ni,1))])
S =  np.hstack([0.5*np.random.random((Ne+Ni, Ne)), -np.random.random((Ne+Ni, Ni))])


In [119]:
v= -65*np.ones((Ne+Ni,1)) # Initial values of v
u=b*v                     # initial values of u
firings = -1*np.ones((2,1))


In [120]:
for t in np.arange(1000):
    I = np.concatenate([5*np.random.normal((Ne,1)), 2*np.random.normal((Ni,1))])
    fired= np.argwhere(v>=30)
    firings = np.hstack([firings, np.array((t+0*fired, fired))])
    break
    

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 3 dimension(s)

In [127]:
np.argwhere(v>=-70), v

(array([[  0,   0],
        [  1,   0],
        [  2,   0],
        ...,
        [997,   0],
        [998,   0],
        [999,   0]], shape=(1000, 2)),
 array([[-65.],
        [-65.],
        [-65.],
        [-65.],
        [-65.],
        [-65.],
        [-65.],
        [-65.],
        [-65.],
        [-65.],
        [-65.],
        [-65.],
        [-65.],
        [-65.],
        [-65.],
        [-65.],
        [-65.],
        [-65.],
        [-65.],
        [-65.],
        [-65.],
        [-65.],
        [-65.],
        [-65.],
        [-65.],
        [-65.],
        [-65.],
        [-65.],
        [-65.],
        [-65.],
        [-65.],
        [-65.],
        [-65.],
        [-65.],
        [-65.],
        [-65.],
        [-65.],
        [-65.],
        [-65.],
        [-65.],
        [-65.],
        [-65.],
        [-65.],
        [-65.],
        [-65.],
        [-65.],
        [-65.],
        [-65.],
        [-65.],
        [-65.],
        [-65.],
        [-65.],
        [-65.],


In [32]:
np.random.normal((5,1))

array([5.5366008 , 1.66547361])

In [113]:
fired = np.array([1,2,3])
fired

array([1, 2, 3])

In [114]:
firings = np.hstack([firings, np.array((t+0*fired, fired))])

In [115]:

firings

array([[-1.,  0.,  0.,  0.],
       [-1.,  1.,  2.,  3.]])

In [67]:
np.array((t+0*fired, fired))

array([[0, 0, 0],
       [1, 2, 3]])

In [70]:
firings

array([], dtype=float64)

In [90]:
np.hstack((np.array((t+0*fired[:1], fired[:1])), np.array((t+0*fired, fired))))

array([[0, 0, 0, 0],
       [1, 1, 2, 3]])